{{- if .Values.cypher.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-openai" .Release.Name) .Values.cypher.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  OPENAI_API_KEY: {{ .Values.cypher.openaiApiCypher | quote }}
  EXA_API_KEY: {{ .Values.cypher.exaApiCypher | quote }}
{{- end }}