{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-openai" .Release.Name) .Values.cypher.name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  OPENAI_API_KEY: {{ .Values.cypher.openaiApiKey | quote }}
{{- end }}